build:
  wharf-web:
    docker:
      file: Dockerfile
      tag: unstable
      args:
        - BUILD_VERSION=${GIT_SAFEBRANCH}
        - BUILD_GIT_COMMIT=${GIT_COMMIT}
        - BUILD_REF=${BUILD_REF}
