build:
  web-ng:
    docker:
      file: Dockerfile
      tag: ${GIT_TAG},latest
      args:
        - WHARF_WEB_VERSION=${GIT_TAG}
        - WHARF_WEB_CI_GIT_COMMIT=${GIT_COMMIT}
        - WHARF_WEB_CI_BUILD_REF=${BUILD_REF}
