/**
 * Wharf provider API for GitHub
 * Wharf backend API for integrating GitHub repositories with the Wharf main API.
 *
 * OpenAPI spec version: v3.0.0
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MainImportBody { 
    group?: string;
    project?: string;
    /**
     * used in refresh only
     */
    projectId?: number;
    /**
     * azuredevops, gitlab or github
     */
    provider?: string;
    /**
     * used in refresh only
     */
    providerId?: number;
    token?: string;
    /**
     * used in refresh only
     */
    tokenId?: number;
    url?: string;
    user?: string;
}
