/**
 * Swagger import API
 * Wharf import server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MainImport { 
    group?: string;
    project?: string;
    /**
     * used in refresh only
     */
    projectId?: number;
    /**
     * azuredevops, gitlab or github
     */
    provider?: string;
    /**
     * used in refresh only
     */
    providerId?: number;
    token?: string;
    /**
     * used in refresh only
     */
    tokenId?: number;
    uploadUrl?: string;
    url?: string;
    user?: string;
}
