/**
 * Swagger import API
 * Wharf import server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MainBuildParam } from './mainBuildParam';


export interface MainBuild { 
    buildId?: number;
    environment?: string;
    finishedOn?: Date;
    gitBranch?: string;
    isInvalid?: boolean;
    params?: Array<MainBuildParam>;
    projectId?: number;
    scheduledOn?: Date;
    stage?: string;
    startedOn?: Date;
    statusId?: number;
}
