/**
 * Wharf main API
 * Wharf backend API that manages data storage for projects, builds, providers, etc.
 *
 * OpenAPI spec version: local docker-compose
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MainBranch } from './mainBranch';
import { MainProvider } from './mainProvider';


export interface MainProject { 
    avatarUrl?: string;
    branches?: Array<MainBranch>;
    /**
     * ParsedBuildDefinition is populated when marshalled via MarshalJSON
     */
    build?: any;
    buildDefinition?: string;
    description?: string;
    gitUrl?: string;
    groupName?: string;
    name?: string;
    projectId?: number;
    provider?: MainProvider;
    providerId?: number;
    tokenId?: number;
}
