/**
 * Wharf main API
 * Wharf backend API that manages data storage for projects, builds, providers, etc.
 *
 * OpenAPI spec version: v4.0.1
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MainBuildParam } from './mainBuildParam';


export interface MainBuild { 
    buildId?: number;
    environment?: string;
    finishedOn?: Date;
    gitBranch?: string;
    isInvalid?: boolean;
    params?: Array<MainBuildParam>;
    projectId?: number;
    scheduledOn?: Date;
    stage?: string;
    startedOn?: Date;
    statusId?: number;
}
