/**
 * Swagger import API
 * Wharf import server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MainBranch } from './mainBranch';
import { MainProvider } from './mainProvider';


export interface MainProject { 
    avatarUrl?: string;
    branches?: Array<MainBranch>;
    buildDefinition?: string;
    description?: string;
    gitUrl?: string;
    groupName?: string;
    name?: string;
    projectId?: number;
    provider?: MainProvider;
    providerId?: number;
    tokenId?: number;
}
