/**
 * Wharf main API
 * Wharf backend API that manages data storage for projects, builds, providers, etc.
 *
 * OpenAPI spec version: v5.0.0-rc.1
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponseBuildParam } from './responseBuildParam';
import { ResponseTestResultListSummary } from './responseTestResultListSummary';
import { ResponseTestResultSummary } from './responseTestResultSummary';


export interface ResponseBuild { 
    buildId?: number;
    createdAt?: Date;
    environment?: string;
    finishedOn?: Date;
    gitBranch?: string;
    isInvalid?: boolean;
    params?: Array<ResponseBuildParam>;
    projectId?: number;
    scheduledOn?: Date;
    stage?: string;
    startedOn?: Date;
    status?: ResponseBuild.StatusEnum;
    statusId?: number;
    testResultListSummary?: ResponseTestResultListSummary;
    testResultSummaries?: Array<ResponseTestResultSummary>;
    updatedAt?: Date;
}
export namespace ResponseBuild {
    export type StatusEnum = 'Scheduling' | 'Running' | 'Completed' | 'Failed';
    export const StatusEnum = {
        Scheduling: 'Scheduling' as StatusEnum,
        Running: 'Running' as StatusEnum,
        Completed: 'Completed' as StatusEnum,
        Failed: 'Failed' as StatusEnum
    };
}
