/**
 * Wharf main API
 * Wharf backend API that manages data storage for projects, builds, providers, etc.
 *
 * OpenAPI spec version: v5.1.2
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponseBranch } from './responseBranch';
import { ResponseProvider } from './responseProvider';


export interface ResponseProject { 
    avatarUrl?: string;
    branches?: Array<ResponseBranch>;
    build?: any;
    buildDefinition?: string;
    createdAt?: Date;
    description?: string;
    gitUrl?: string;
    groupName?: string;
    name?: string;
    projectId?: number;
    provider?: ResponseProvider;
    providerId?: number;
    remoteProjectId?: string;
    tokenId?: number;
    updatedAt?: Date;
}
