/**
 * Wharf main API
 * Wharf backend API that manages data storage for projects, builds, providers, etc.
 *
 * OpenAPI spec version: v5.1.2
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ResponseTestResultDetail { 
    artifactId?: number;
    buildId?: number;
    completedOn?: Date;
    createdAt?: Date;
    message?: string;
    name?: string;
    startedOn?: Date;
    status?: ResponseTestResultDetail.StatusEnum;
    testResultDetailId?: number;
    updatedAt?: Date;
}
export namespace ResponseTestResultDetail {
    export type StatusEnum = 'Failed' | 'Passed' | 'Skipped';
    export const StatusEnum = {
        Failed: 'Failed' as StatusEnum,
        Passed: 'Passed' as StatusEnum,
        Skipped: 'Skipped' as StatusEnum
    };
}
