export * from './artifact.service';
import { ArtifactService } from './artifact.service';
export * from './branch.service';
import { BranchService } from './branch.service';
export * from './branches.service';
import { BranchesService } from './branches.service';
export * from './build.service';
import { BuildService } from './build.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './meta.service';
import { MetaService } from './meta.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './provider.service';
import { ProviderService } from './provider.service';
export * from './testResult.service';
import { TestResultService } from './testResult.service';
export * from './token.service';
import { TokenService } from './token.service';
export const APIS = [ArtifactService, BranchService, BranchesService, BuildService, HealthService, MetaService, ProjectService, ProviderService, TestResultService, TokenService];
