/**
 * Wharf main API
 * Wharf backend API that manages data storage for projects, builds, providers, etc.
 *
 * OpenAPI spec version: v4.1.0
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { MainArtifact } from '../model/mainArtifact';
import { MainTestsResults } from '../model/mainTestsResults';
import { ProblemResponse } from '../model/problemResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ArtifactService {

    protected basePath = 'https://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get build artifact
     * 
     * @param buildid Build ID
     * @param artifactId Artifact ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buildBuildidArtifactArtifactIdGet(buildid: number, artifactId: number, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public buildBuildidArtifactArtifactIdGet(buildid: number, artifactId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public buildBuildidArtifactArtifactIdGet(buildid: number, artifactId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public buildBuildidArtifactArtifactIdGet(buildid: number, artifactId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (buildid === null || buildid === undefined) {
            throw new Error('Required parameter buildid was null or undefined when calling buildBuildidArtifactArtifactIdGet.');
        }

        if (artifactId === null || artifactId === undefined) {
            throw new Error('Required parameter artifactId was null or undefined when calling buildBuildidArtifactArtifactIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get(`${this.basePath}/build/${encodeURIComponent(String(buildid))}/artifact/${encodeURIComponent(String(artifactId))}`,
            {
                responseType: "blob",
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Post build artifact
     * 
     * @param buildid Build ID
     * @param file build artifact file
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buildBuildidArtifactPost(buildid: number, file: Blob, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public buildBuildidArtifactPost(buildid: number, file: Blob, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public buildBuildidArtifactPost(buildid: number, file: Blob, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public buildBuildidArtifactPost(buildid: number, file: Blob, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (buildid === null || buildid === undefined) {
            throw new Error('Required parameter buildid was null or undefined when calling buildBuildidArtifactPost.');
        }

        if (file === null || file === undefined) {
            throw new Error('Required parameter file was null or undefined when calling buildBuildidArtifactPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void | HttpParams; };
        let useForm = false;
        let convertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (file !== undefined) {
            formParams = formParams.append('file', <any>file) || formParams;
        }

        return this.httpClient.post<any>(`${this.basePath}/build/${encodeURIComponent(String(buildid))}/artifact`,
            convertFormParamsToString ? formParams.toString() : formParams,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get list of build artifacts
     * 
     * @param buildid Build ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buildBuildidArtifactsGet(buildid: number, observe?: 'body', reportProgress?: boolean): Observable<Array<MainArtifact>>;
    public buildBuildidArtifactsGet(buildid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<MainArtifact>>>;
    public buildBuildidArtifactsGet(buildid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<MainArtifact>>>;
    public buildBuildidArtifactsGet(buildid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (buildid === null || buildid === undefined) {
            throw new Error('Required parameter buildid was null or undefined when calling buildBuildidArtifactsGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<MainArtifact>>(`${this.basePath}/build/${encodeURIComponent(String(buildid))}/artifacts`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get build tests results from .trx files
     * 
     * @param buildid Build ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buildBuildidTestsResultsGet(buildid: number, observe?: 'body', reportProgress?: boolean): Observable<MainTestsResults>;
    public buildBuildidTestsResultsGet(buildid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MainTestsResults>>;
    public buildBuildidTestsResultsGet(buildid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MainTestsResults>>;
    public buildBuildidTestsResultsGet(buildid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (buildid === null || buildid === undefined) {
            throw new Error('Required parameter buildid was null or undefined when calling buildBuildidTestsResultsGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<MainTestsResults>(`${this.basePath}/build/${encodeURIComponent(String(buildid))}/tests-results`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
