/**
 * Wharf main API
 * Wharf backend API that manages data storage for projects, builds, providers, etc.
 *
 * OpenAPI spec version: v5.1.1
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DeprecatedBranch } from '../model/deprecatedBranch';
import { ProblemResponse } from '../model/problemResponse';
import { ResponseBranch } from '../model/responseBranch';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class BranchesService {

    protected basePath = 'https://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Resets branches for a project
     * Alters the database by removing, adding and updating until the stored branches equals the input branches. Deprecated since v5.0.0. Planned for removal in v6.0.0. Use PUT /project/{projectId}/branch instead. Added in v1.0.0.
     * @param branches branch array
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public oldUpdateProjectBranchList(branches: Array<DeprecatedBranch>, observe?: 'body', reportProgress?: boolean): Observable<Array<ResponseBranch>>;
    public oldUpdateProjectBranchList(branches: Array<DeprecatedBranch>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ResponseBranch>>>;
    public oldUpdateProjectBranchList(branches: Array<DeprecatedBranch>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ResponseBranch>>>;
    public oldUpdateProjectBranchList(branches: Array<DeprecatedBranch>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (branches === null || branches === undefined) {
            throw new Error('Required parameter branches was null or undefined when calling oldUpdateProjectBranchList.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Array<ResponseBranch>>(`${this.basePath}/branches`,
            branches,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
