/**
 * Wharf main API
 * Wharf backend API that manages data storage for projects, builds, providers, etc.
 *
 * OpenAPI spec version: v4.2.0
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { MainProvider } from '../model/mainProvider';
import { ProblemResponse } from '../model/problemResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ProviderService {

    protected basePath = 'https://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add provider to database.
     * Add provider to database. Token in post object has to exists or should be empty. Token will has to be updated Provider ID during this operation.
     * @param provider provider object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public providerPost(provider?: MainProvider, observe?: 'body', reportProgress?: boolean): Observable<MainProvider>;
    public providerPost(provider?: MainProvider, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MainProvider>>;
    public providerPost(provider?: MainProvider, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MainProvider>>;
    public providerPost(provider?: MainProvider, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MainProvider>(`${this.basePath}/provider`,
            provider,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns provider with selected provider ID
     * 
     * @param providerid Provider ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public providerProvideridGet(providerid: number, observe?: 'body', reportProgress?: boolean): Observable<MainProvider>;
    public providerProvideridGet(providerid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MainProvider>>;
    public providerProvideridGet(providerid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MainProvider>>;
    public providerProvideridGet(providerid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (providerid === null || providerid === undefined) {
            throw new Error('Required parameter providerid was null or undefined when calling providerProvideridGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<MainProvider>(`${this.basePath}/provider/${encodeURIComponent(String(providerid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Put provider in database.
     * Creates a new provider if a match is not found.
     * @param provider provider object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public providerPut(provider?: MainProvider, observe?: 'body', reportProgress?: boolean): Observable<MainProvider>;
    public providerPut(provider?: MainProvider, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MainProvider>>;
    public providerPut(provider?: MainProvider, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MainProvider>>;
    public providerPut(provider?: MainProvider, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<MainProvider>(`${this.basePath}/provider`,
            provider,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns first 100 providers
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public providersGet(observe?: 'body', reportProgress?: boolean): Observable<Array<MainProvider>>;
    public providersGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<MainProvider>>>;
    public providersGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<MainProvider>>>;
    public providersGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<MainProvider>>(`${this.basePath}/providers`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns arrays of providers that match to search criteria.
     * Returns arrays of providers that match to search criteria. It takes into consideration name, URL, UploadURL and token ID.
     * @param provider provider object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public providersSearchPost(provider?: MainProvider, observe?: 'body', reportProgress?: boolean): Observable<Array<MainProvider>>;
    public providersSearchPost(provider?: MainProvider, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<MainProvider>>>;
    public providersSearchPost(provider?: MainProvider, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<MainProvider>>>;
    public providersSearchPost(provider?: MainProvider, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<MainProvider>>(`${this.basePath}/providers/search`,
            provider,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
