/**
 * Wharf main API
 * Wharf backend API that manages data storage for projects, builds, providers, etc.
 *
 * OpenAPI spec version: local docker-compose
 * Contact: wharf@iver.se
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { MainToken } from '../model/mainToken';
import { MainTokenWithProviderID } from '../model/mainTokenWithProviderID';
import { ProblemResponse } from '../model/problemResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TokenService {

    protected basePath = 'https://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add token to database.
     * Add token to database. Provider in post object has to exists or should be empty.
     * @param token token object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tokenPost(token?: MainTokenWithProviderID, observe?: 'body', reportProgress?: boolean): Observable<MainToken>;
    public tokenPost(token?: MainTokenWithProviderID, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MainToken>>;
    public tokenPost(token?: MainTokenWithProviderID, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MainToken>>;
    public tokenPost(token?: MainTokenWithProviderID, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MainToken>(`${this.basePath}/token`,
            token,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Put token in database.
     * Creates a new token if a match is not found.
     * @param token token object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tokenPut(token?: MainTokenWithProviderID, observe?: 'body', reportProgress?: boolean): Observable<MainToken>;
    public tokenPut(token?: MainTokenWithProviderID, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MainToken>>;
    public tokenPut(token?: MainTokenWithProviderID, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MainToken>>;
    public tokenPut(token?: MainTokenWithProviderID, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<MainToken>(`${this.basePath}/token`,
            token,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns token with selected token ID
     * 
     * @param tokenid Token ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tokenTokenidGet(tokenid: number, observe?: 'body', reportProgress?: boolean): Observable<MainToken>;
    public tokenTokenidGet(tokenid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MainToken>>;
    public tokenTokenidGet(tokenid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MainToken>>;
    public tokenTokenidGet(tokenid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tokenid === null || tokenid === undefined) {
            throw new Error('Required parameter tokenid was null or undefined when calling tokenTokenidGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<MainToken>(`${this.basePath}/token/${encodeURIComponent(String(tokenid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns first 100 tokens
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tokensGet(observe?: 'body', reportProgress?: boolean): Observable<Array<MainToken>>;
    public tokensGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<MainToken>>>;
    public tokensGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<MainToken>>>;
    public tokensGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<MainToken>>(`${this.basePath}/tokens`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns arrays of tokens that match to search criteria.
     * Returns arrays of tokens that match to search criteria. It takes into consideration only token string and user name.
     * @param token token object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tokensSearchPost(token?: MainToken, observe?: 'body', reportProgress?: boolean): Observable<Array<MainToken>>;
    public tokensSearchPost(token?: MainToken, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<MainToken>>>;
    public tokensSearchPost(token?: MainToken, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<MainToken>>>;
    public tokensSearchPost(token?: MainToken, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<MainToken>>(`${this.basePath}/tokens/search`,
            token,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
